import React, { useState } from 'react'
import { ArrowLeft, Shield, AlertTriangle, FileText } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { useUser } from '../context/UserContext'
import RecordButton from '../components/RecordButton'
import ShareButton from '../components/ShareButton'

export default function Encounter() {
  const navigate = useNavigate()
  const { user, selectedState, addEncounter, isPremium } = useUser()
  const [hasRecording, setHasRecording] = useState(false)
  const [notes, setNotes] = useState('')
  const [currentRecording, setCurrentRecording] = useState(null)
  const [showSaveForm, setShowSaveForm] = useState(false)

  const handleRecordingComplete = (audioBlob) => {
    setCurrentRecording(audioBlob)
    setHasRecording(true)
    setShowSaveForm(true)
    
    // In a real app, you would upload to IPFS/Pinata here
    console.log('Recording completed:', audioBlob)
  }

  const handleSaveEncounter = () => {
    const encounter = {
      audioFilePath: hasRecording ? 'mock-audio-url' : null,
      notes: notes.trim() || null,
      sharedContent: null
    }
    
    addEncounter(encounter)
    
    // Reset state
    setHasRecording(false)
    setCurrentRecording(null)
    setNotes('')
    setShowSaveForm(false)
    
    // Navigate back to dashboard
    navigate('/dashboard')
  }

  const generateShareableContent = () => {
    const timestamp = new Date().toLocaleString()
    return `Encounter Documentation - ${timestamp}\n\nLocation: ${selectedState}\nRecording: ${hasRecording ? 'Yes' : 'No'}\nNotes: ${notes || 'None'}\n\nGenerated by Shield Rights`
  }

  return (
    <div className="min-h-screen pb-20">
      {/* Header */}
      <div className="flex items-center justify-between p-4 border-b border-white/20">
        <Link
          to="/dashboard"
          className="p-2 hover:bg-white/10 rounded-lg transition-colors"
        >
          <ArrowLeft className="text-white" size={24} />
        </Link>
        
        <h1 className="text-white font-semibold">Record Encounter</h1>
        
        <div className="w-10" />
      </div>

      <div className="px-4 py-6">
        {!showSaveForm ? (
          <>
            {/* Safety Notice */}
            <div className="bg-red-500/20 border border-red-500/30 rounded-lg p-4 mb-8">
              <div className="flex items-start space-x-3">
                <AlertTriangle className="text-red-400 flex-shrink-0 mt-0.5" size={20} />
                <div>
                  <h4 className="text-red-100 font-medium text-sm mb-1">
                    Safety First
                  </h4>
                  <p className="text-red-100/80 text-sm">
                    Recording laws vary by state. In some states, you must inform the other party. 
                    Always prioritize your safety over recording.
                  </p>
                </div>
              </div>
            </div>

            {/* Recording Interface */}
            <div className="text-center mb-8">
              <div className="bg-white/10 backdrop-blur-md border border-white/20 rounded-2xl p-8 mb-6">
                <h2 className="text-white text-xl font-semibold mb-4">
                  {hasRecording ? 'Recording Saved' : 'Tap to Start Recording'}
                </h2>
                
                <RecordButton
                  onRecordingComplete={handleRecordingComplete}
                  disabled={!isPremium && hasRecording}
                />
                
                {!isPremium && (
                  <p className="text-white/60 text-xs mt-4">
                    Free users limited to one recording. 
                    <Link to="/settings" className="text-accent hover:underline ml-1">
                      Upgrade for unlimited
                    </Link>
                  </p>
                )}
              </div>
              
              {hasRecording && (
                <button
                  onClick={() => setShowSaveForm(true)}
                  className="bg-accent hover:bg-accent/90 text-black font-semibold py-3 px-6 rounded-lg transition-colors"
                >
                  Save & Continue
                </button>
              )}
            </div>

            {/* Quick Rights Reference */}
            <div className="bg-white/10 backdrop-blur-md border border-white/20 rounded-lg p-6">
              <div className="flex items-center space-x-3 mb-4">
                <Shield className="text-white" size={20} />
                <h3 className="text-white font-semibold">Quick Rights Reminder</h3>
              </div>
              
              <div className="space-y-3 text-white/90 text-sm">
                <div>• You have the right to remain silent</div>
                <div>• You have the right to record (in most states)</div>
                <div>• Ask "Am I free to leave?"</div>
                <div>• You have the right to an attorney</div>
              </div>
              
              <Link
                to="/rights"
                className="inline-block mt-4 text-accent hover:text-accent/80 text-sm font-medium transition-colors"
              >
                View full rights card →
              </Link>
            </div>
          </>
        ) : (
          /* Save Encounter Form */
          <div className="space-y-6 animate-slide-up">
            <div className="text-center">
              <FileText className="text-white mx-auto mb-4" size={32} />
              <h2 className="text-white text-xl font-semibold mb-2">
                Document Your Encounter
              </h2>
              <p className="text-white/70">
                Add notes and save this encounter for your records
              </p>
            </div>
            
            <div className="bg-white/10 backdrop-blur-md border border-white/20 rounded-lg p-6">
              <h3 className="text-white font-medium mb-4">Encounter Details</h3>
              
              <div className="space-y-4">
                <div>
                  <label className="block text-white/80 text-sm font-medium mb-2">
                    Date & Time
                  </label>
                  <div className="text-white bg-white/5 px-3 py-2 rounded-lg text-sm">
                    {new Date().toLocaleString()}
                  </div>
                </div>
                
                <div>
                  <label className="block text-white/80 text-sm font-medium mb-2">
                    Location/State
                  </label>
                  <div className="text-white bg-white/5 px-3 py-2 rounded-lg text-sm">
                    {selectedState}
                  </div>
                </div>
                
                <div>
                  <label className="block text-white/80 text-sm font-medium mb-2">
                    Audio Recording
                  </label>
                  <div className="text-white bg-white/5 px-3 py-2 rounded-lg text-sm">
                    {hasRecording ? '✓ Recording saved' : '✗ No recording'}
                  </div>
                </div>
                
                <div>
                  <label htmlFor="notes" className="block text-white/80 text-sm font-medium mb-2">
                    Notes (Optional)
                  </label>
                  <textarea
                    id="notes"
                    value={notes}
                    onChange={(e) => setNotes(e.target.value)}
                    placeholder="What happened? Who was involved? Any important details..."
                    className="w-full px-3 py-2 bg-white/10 border border-white/20 rounded-lg text-white placeholder-white/50 focus:outline-none focus:ring-2 focus:ring-accent focus:border-transparent resize-none"
                    rows={4}
                  />
                </div>
              </div>
            </div>
            
            <ShareButton
              content={generateShareableContent()}
              title="Encounter Documentation"
            />
            
            <div className="flex space-x-3">
              <button
                onClick={() => setShowSaveForm(false)}
                className="flex-1 bg-white/10 hover:bg-white/20 text-white font-medium py-3 px-6 rounded-lg transition-colors"
              >
                Back
              </button>
              
              <button
                onClick={handleSaveEncounter}
                className="flex-1 bg-accent hover:bg-accent/90 text-black font-semibold py-3 px-6 rounded-lg transition-colors"
              >
                Save Encounter
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}